apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-sample-app
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: flask-app
        image: rohsun/my-flask-app:83
        ports:
        - containerPort: 5000

